haupt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gebäude.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gebäude/models.py
from django.db import models
from django.core.exceptions import ValidationError
import datetime


def zusässige_negative(value):
    if value >= 0 :
        raise ValidationError(
            '%(value)s ist keine negative Zahl',
            params={'value': value},
        )
def zusässige_posetive(value):
    if value <= 0:
        raise ValidationError(
            '%(value)s ist keine posetive Zahl',
            params={'value': value},
        )

class Objekte(models.Model):
    name = models.CharField(max_length=150)
    address = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Kosten(models.Model):
    objekte = models.ForeignKey(Objekte, on_delete=models.CASCADE)
    kosten = models.IntegerField(blank=True, null=True)
    einnahmen = models.IntegerField(blank=True, null=True)
    #kosten = models.IntegerField(validators=[zusässige_negative], blank=True)
    #einnahmen = models.IntegerField(validators=[zusässige_posetive], blank=True)
    von_wem = models.CharField(max_length=150, blank=True)
    Datum = models.DateField(default= datetime.datetime.now)
    #Dokument = models.ImageField(upload_to="dokument/", blank=True)
    Dokument = models.FileField(upload_to="dokument/", blank=True)
    
    def __str__(self):
         return f"Kosten für {self.objekte}"



class Technik(models.Model):
    objekt = models.ForeignKey(Objekte, on_delete=models.CASCADE)
    gegenstand = models.CharField(max_length=200)
    wohnung = models.CharField(max_length=200)


class Mietern(models.Model):
    objekt = models.ForeignKey(Objekte, on_delete=models.CASCADE)
    vornanme = models.CharField(max_length=200)
    nachname = models.CharField(max_length=200)
    monats_miethe = models.IntegerField(validators=[zusässige_posetive], blank=True)
    kaution = models.IntegerField(validators=[zusässige_posetive], blank=True)
    wohnung = models.IntegerField(blank=True, null=True)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Document{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Name der Objekte
                        </a>
                        <ul class="dropdown-menu">
                            {% for objekt in objekte %}
                            <li class="dropdown-submenu">
                                <a class="dropdown-item" tabindex="-1" href="#">{{ objekt.name }}</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'details' objekt.id %}">Details anzeigen</a></li>
                                    <li class="dropdown-submenu">
                                        <a class="dropdown-item" href="#">Wohnungen anzeigen</a>
                                        <ul class="dropdown-menu">
                                            {% for mieter in objekt.mietern_set.all %}
                                            <li><a class="dropdown-item" href="{% url 'wohnung-details' mieter.id %}">Wohnung {{ mieter.wohnung }} - {{ mieter.vorname }} {{ mieter.nachname }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'objekte' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'objekt_erstellen' %}">Neue Gebäude eintragen</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mietern_erstellen' %}">Neue Mieter eintragen</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'technik_erstellen' %}">Neue Technik eintragen</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'kosten_erstellen' %}">Neue Kosten eintragen</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main>
        {% block content %}
        <!-- Hauptinhalt wird hier eingefügt -->
        {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            document.querySelectorAll('.dropdown-submenu > a').forEach(function(element) {
                element.addEventListener('click', function(e) {
                    e.preventDefault();
                    e.stopPropagation();
                    if (e.target.nextElementSibling) {
                        e.target.nextElementSibling.classList.toggle('show');
                    }
                });
            });
        });
    </script>

    <style>
        .dropdown-submenu .dropdown-menu {
            display: none;
        }
        .dropdown-submenu .dropdown-menu.show {
            display: block;
            margin-left: 20px;
            margin-top: -1px;
        }
    </style>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container d-flex flex-column align-items-center mt-5">
    <h1>Dashboard</h1>
    <div class="row w-100 justify-content-center">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header">
                    <h3>Objekte</h3>
                </div>
                <div class="card-body">
                    <ul>
                        {% for objekt in objekte %}
                        <li>{{ objekt.name }} - {{ objekt.address }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header">
                    <h3>Finanzübersicht</h3>
                </div>
                <div class="card-body">
                    <p>Gesamtsumme der Miete: {{ gesamtsumme_miete }}€</p>
                    <p>Gesamtsumme der Kosten: {{ gesamtsumme_kosten }}€</p>
                    <p>Gewinn/Verlust: {{ gewinn_verlust }}€</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row w-100 justify-content-center mt-4">
        <div class="col-md-10">
            <div class="card mb-4">
                <div class="card-header">
                    <h3>Chart</h3>
                </div>
                <div class="card-body">
                    {{ chart|safe }}
                </div>
            </div>
        </div>
    </div>
    <a href="{% url 'objekte' %}" class="btn btn-primary mt-3">Zurück zur Liste</a>
</div>
{% endblock %}

templates/form_eintragen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Objekt erstellen</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1>Objekt erstellen</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Speichern</button>
        </form>
        {% if form.errors %}
            <div class="alert alert-danger mt-3">
                <h4>Fehler:</h4>
                <ul>
                    {% for field, errors in form.errors.items %}
                        <li>{{ field }}: {{ errors }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
</body>
</html>

templates/form_eintragen_kosten.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eintragen Kosten</title>
</head>
<body>
    <h1>Eintrag erstellen</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Speichern</button>
    </form>
</body>
</html>

templates/form_eintragen_mieter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eintragen Kosten</title>
</head>
<body>
    <h1>Eintrag erstellen</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Speichern</button>
    </form>
</body>
</html>

templates/form_eintragen_technik.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eintragen Kosten</title>
</head>
<body>
    <h1>Eintrag erstellen</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Speichern</button>
    </form>
</body>
</html>

templates/technik.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Technikdetails für {{ objekt.name }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<div class="container d-flex flex-column align-items-center mt-5">
    <div class="p-3 mb-2 bg-primary text-white">
    <h1>Technikdetails für {{ objekt.name }}</h1>

    <h2>Mieter pro Wohnung:</h2>
    {% for wohnung in wohnungen %}
    <h3>Wohnung {{ wohnung }}</h3>
    <ul>
        {% for mieter in mietern %}
            {% if mieter.wohnung == wohnung %}
                <li>{{ mieter.vorname }} {{ mieter.nachname }} - Miete: {{ mieter.monats_miete }} - Kaution: {{ mieter.kaution }}€</li>
            {% endif %}
        {% endfor %}
    </ul>
    {% endfor %}

    <h2>Technik:</h2>
    <ul>
        {% for tech in technik %}
        <li>{{ tech.gegenstand }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'objekte' %}">Zurück zur Liste</a>
</div>
</div>
</body>
</html>

templates/test.html
{% extends "base.html" %}

{% block title %}Startseite - Home{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>Beschreibung</h1>
    <p>
        Das Projekt "Mietobjekte" ermöglicht die Verwaltung von Immobilien, einschließlich der Kosten,
        technischen Ausstattung und Mieterinformationen über eine benutzerfreundliche Oberfläche. Derzeit
        erfolgt die Dateneingabe über die Admin-Oberfläche und über die HTML-Oberfläche.
    </p>

    <h2>Funktionalitäten</h2>
    <ul>
        <li>
            <strong>Objektverwaltung:</strong> Verwalte die zentralen Informationen zu den Mietobjekten,
            einschließlich Name, Adresse und relevanter Details.
        </li>
        <li>
            <strong>Kostenmanagement:</strong> Erfasse und verfolge die Kosten und Einnahmen für jedes
            Mietobjekt. Jeder Kostenposten kann mit einem Dokument verknüpft werden, um Transparenz und
            Nachvollziehbarkeit zu gewährleisten.
        </li>
        <li>
            <strong>Technikverzeichnis:</strong> Halte eine Übersicht über die technische Ausstattung jedes
            Mietobjekts. Dies umfasst Details zu den installierten Geräten und technischen Einrichtungen.
        </li>
        <li>
            <strong>Mieterinformationen:</strong> Verwalte Informationen zu den Mietern jedes Objekts,
            einschließlich ihrer persönlichen Daten, zugewiesener Wohnung und Mietkonditionen wie monatliche
            Miete und Kaution.
        </li>
        <li>
            <strong>Navigationsmenü:</strong> Eine kombinierte Navbar und ein Dropdown-Menü, implementiert
            mit Bootstrap und benutzerdefiniertem JavaScript, ermöglichen eine einfache Navigation zwischen
            allen Mietobjekten. Dadurch können Nutzer schnell und effizient zu jedem gewünschten Objekt
            navigieren.
        </li>
    </ul>

    <h2>Datenbank</h2>
    <p>
        Das Projekt verwendet SQLite als Datenbankmanagementsystem. SQLite bietet eine einfache,
        leichtgewichtige Lösung für kleine bis mittelgroße Anwendungen und ist direkt in das Projekt
        integriert.
    </p>

    <h2>Beispielanwendungen</h2>
    <ul>
        <li>
            <strong>Beispielhafte Daten:</strong> Das Projekt enthält vordefinierte Beispieldaten, die die
            Funktionalitäten der Anwendung demonstrieren. Diese Daten sind so strukturiert, dass sie die
            Verwaltung mehrerer Mietobjekte und deren Attribute zeigen.
        </li>
    </ul>

    <h2>Zukünftige Entwicklung</h2>
    <p>
        Das Projekt wird kontinuierlich weiterentwickelt. Potenzielle zukünftige Erweiterungen könnten eine
        benutzerfreundliche Oberfläche für Endbenutzer sowie erweiterte Funktionen zur Berichterstellung und
        Analyse umfassen.
    </p>
</div>
{% endblock %}

templates/test_details.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %} Details of the Object {% endblock %}

{% block content %}
<div class="d-flex flex-column align-items-center">
    <h1>Details des Objekts</h1>
    <p>Name: {{ objekt.name }}</p>
    <p>Adresse: {{ objekt.address }}</p>
    <p>Kosten:</p>
    <ul>
        {% load custom_filters %}
        {% for kosten in objekt.kosten_set.all %}
        <li>{{ kosten.von_wem }}: {{ kosten.kosten }}€
            {% if kosten.Dokument %}
                {% if kosten.Dokument.url|is_pdf %}
                    <a href="{{ kosten.Dokument.url }}" target="_blank">Dokument ansehen (PDF)</a>
                {% else %}
                    <img src="{{ kosten.Dokument.url }}" alt="Dokument">
                {% endif %}
            {% endif %}
            ({{ kosten.Datum }})
        </li>
        {% endfor %}
    </ul>
    <p>Technik:</p>
    <ul>
        {% for technik in objekt.technik_set.all %}
        <li>{{ technik.gegenstand }} in {{ technik.wohnung }}</li>
        {% endfor %}
    </ul>
    <p>Mieter:</p>
    <ul>
        {% for mieter in objekt.mietern_set.all %}
        <li>{{ mieter.vornanme }} {{ mieter.nachname }}, Wohung{{mieter.wohnung}} - Miete: {{ mieter.monats_miethe }}€ - Kaution: {{ mieter.kaution }}€</li>
        {% endfor %}
    </ul>
    <h2>Finanzübersicht:</h2>
    <p>Gesamtsumme der Miete: {{ gesamtsumme_miete }}€</p>
    <p>Gesamtsumme der Kosten: {{ gesamtsumme_kosten }}€</p>
    <p>Gewinn/Verlust: {{ gewinn_verlust }}€</p>
    <a href="{% url 'objekte' %}">Zurück zur Liste</a>
</div>
{% endblock %}

templates/wohnung_details.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %} {{objekt.wohnung}} {% endblock %}

{% block content %}
<body>
    <div class="container d-flex flex-column align-items-center mt-5">
        <div class="p-3 mb-2 bg-primary text-white">
        <h1>Details der Wohnung {{ mieter.wohnung }}</h1>

        <h2>Mieter</h2>
        <ul>
            <li>Name: {{ mieter.vornanme }} {{ mieter.nachname }}</li>
            <li>Monatliche Miete: {{ mieter.monats_miethe }}€</li>
            <li>Kaution: {{ mieter.kaution }}€</li>
        </ul>

        <h2>Technik Ausstattung</h2>
        <ul>
            {% for tech in technik %}
            <li>{{ tech.gegenstand }}</li>
            {% empty %}
            <li>Keine Technik Ausstattung</li>
            {% endfor %}
        </ul>
    </div>
    <a href="{% url 'objekte' %}">Zurück zur Liste</a>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+CVt8G+z5CQmRXf+2kdqS0coKkFGp" crossorigin="anonymous"></script>
    
</div>
</body>
{% endblock %}